import Box from "@mui/material/Box";
import { DataGrid, GridColDef } from "@mui/x-data-grid";

const columns: GridColDef[] = [
  { field: "_id", headerName: "ID", width: 40 },
  {
    field: "city",
    headerName: "City",
    width: 150,
    editable: true,
  },
  {
    field: "community_area",
    headerName: "Community Area",
    width: 150,
    editable: true,
  },
  {
    field: "lat",
    headerName: "Latitude",
    type: "number",
    width: 100,
    editable: true,
  },
  {
    field: "lng",
    headerName: "Longitude",
    type: "number",
    width: 120,
    editable: true,
  },
  {
    field: "neighborhood",
    headerName: "Neighborhood",
    width: 150,
    editable: true,
  },
  {
    field: "ride_count",
    headerName: "Ride Count",
    type: "number",
    width: 120,
    editable: true,
  },
  {
    field: "station_name",
    headerName: "Station Name",
    width: 200,
    editable: true,
  },
  {
    field: "ward",
    headerName: "Ward",
    width: 80,
    editable: true,
  },
];

// Assuming you have the data array as jsonData
const jsonData = [
  {
    _id: "Public Rack - Linder Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 39,
    station_name: "Public Rack - Linder Ave & Belmont Ave",
    ward: "30",
  },
  {
    _id: "Menard Ave & Dakin St - midblock",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.95,
    lng: -87.77,
    neighborhood: "Portage Park",
    ride_count: 13,
    station_name: "Menard Ave & Dakin St - midblock",
    ward: "38",
  },
  {
    _id: "Linder Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 6,
    station_name: "Linder Ave & Belmont Ave",
    ward: "30",
  },
  {
    _id: "Milwaukee Ave & Cuyler Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.9544705,
    lng: -87.7495245,
    neighborhood: "Portage Park",
    ride_count: 834,
    station_name: "Milwaukee Ave & Cuyler Ave",
    ward: "45",
  },
  {
    _id: "Menard Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.77,
    neighborhood: "Portage Park",
    ride_count: 5,
    station_name: "Menard Ave & Belmont Ave",
    ward: "30",
  },
  {
    _id: "Cicero Ave & Roscoe St",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.75,
    neighborhood: "Portage Park",
    ride_count: 18,
    station_name: "Cicero Ave & Roscoe St",
    ward: "31",
  },
  {
    _id: "Public Rack - Laramie Ave & Warwick Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.95,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 36,
    station_name: "Public Rack - Laramie Ave & Warwick Ave",
    ward: "38",
  },
  {
    _id: "Public Rack - Menard Ave & Dakin St - midblock",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.95,
    lng: -87.77,
    neighborhood: "Portage Park",
    ride_count: 44,
    station_name: "Public Rack - Menard Ave & Dakin St - midblock",
    ward: "38",
  },
  {
    _id: "Laramie Ave & Warwick Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.95,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 3,
    station_name: "Laramie Ave & Warwick Ave",
    ward: "38",
  },
  {
    _id: "Public Rack - Menard Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.77,
    neighborhood: "Portage Park",
    ride_count: 10,
    station_name: "Public Rack - Menard Ave & Belmont Ave",
    ward: "30",
  },
  {
    _id: "Cicero Ave & Wellington Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.75,
    neighborhood: "Portage Park",
    ride_count: 85,
    station_name: "Cicero Ave & Wellington Ave",
    ward: "31",
  },
  {
    _id: "Laramie Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 26,
    station_name: "Laramie Ave & Belmont Ave",
    ward: "30",
  },
  {
    _id: "Chopin Park",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 4,
    station_name: "Chopin Park",
    ward: "30",
  },
  {
    _id: "Cicero Ave & Grace St",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.95,
    lng: -87.75,
    neighborhood: "Portage Park",
    ride_count: 202,
    station_name: "Cicero Ave & Grace St",
    ward: "45",
  },
  {
    _id: "Long Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 364,
    station_name: "Long Ave & Belmont Ave",
    ward: "30",
  },
  {
    _id: "Public Rack - Chopin Park",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 60,
    station_name: "Public Rack - Chopin Park",
    ward: "30",
  },
  {
    _id: "Lamon Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.75,
    neighborhood: "Portage Park",
    ride_count: 669,
    station_name: "Lamon Ave & Belmont Ave",
    ward: "31",
  },
  {
    _id: "Mason Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.77,
    neighborhood: "Portage Park",
    ride_count: 140,
    station_name: "Mason Ave & Belmont Ave",
    ward: "30",
  },
  {
    _id: "Public Rack - Cicero Ave & Roscoe St",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.75,
    neighborhood: "Portage Park",
    ride_count: 80,
    station_name: "Public Rack - Cicero Ave & Roscoe St",
    ward: "31",
  },
  {
    _id: "Long & Irving Park",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.95,
    lng: -87.76,
    neighborhood: "Portage Park",
    ride_count: 935,
    station_name: "Long & Irving Park",
    ward: "38",
  },
  {
    _id: "Public Rack - Cicero Ave & Wellington Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.75,
    neighborhood: "Portage Park",
    ride_count: 47,
    station_name: "Public Rack - Cicero Ave & Wellington Ave",
    ward: "31",
  },
  {
    _id: "Central Ave & Roscoe St",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.77,
    neighborhood: "Portage Park",
    ride_count: 379,
    station_name: "Central Ave & Roscoe St",
    ward: "30",
  },
  {
    _id: "Public Rack - Laramie Ave & Belmont Ave",
    city: "Chicago",
    community_area: "Portage park",
    lat: 41.94,
    lng: -87.75,
    neighborhood: "Portage Park",
    ride_count: 95,
    station_name: "Public Rack - Laramie Ave & Belmont Ave",
    ward: "31",
  },
];

export default function Message3() {
  return (
    <Box sx={{ height: 400, width: "100%" }}>
      <DataGrid
        rows={jsonData}
        columns={columns}
        pagination
        //pageSize={5}
        checkboxSelection
        //disableSelectionOnClick
      />
    </Box>
  );
}
